development:
  adapter: postgresql
  encoding: unicode
  database: youtube_share
  pool: 5
  username: postgres
  password: olamilekan
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: youtube_share_test
  pool: 5
  username: postgres
  password: olamilekan
  timeout: 5000